# Generated by Django 2.2 on 2020-05-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200503_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='info',
            new_name='content',
        ),
    ]
