# Generated by Django 2.2 on 2020-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
