# Generated by Django 2.2 on 2020-05-26 01:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
